# Generated by Django 2.2.16 on 2022-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_preuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preuser',
            name='code',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
