# Generated by Django 2.2.16 on 2022-09-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220906_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preuser',
            name='code',
            field=models.CharField(max_length=150),
        ),
    ]
