# Generated by Django 2.2.16 on 2022-09-07 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220906_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreUser',
        ),
    ]
