# Generated by Django 2.2.16 on 2022-09-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220910_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, through='reviews.TitleGenre', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
